### PR TITLE
Add xc7k160t-marble with bscan_spi_xc7k160t_marble.bit

### PR DESCRIPTION
**Pull request by duqiang**
Tested on [BerkeleyLab Marble](https://github.com/BerkeleyLab/Marble/) board

### CODE REVIEW

**Comment by duqiang** [comment]
Because the existing xc7k160t uses package fbg484-1, not the Marble board's ffg676-2.

**Comment by jordens** [comment]
https://github.com/quartiq/bscan_spi_bitstreams/blob/f29f48a1f3fbbd304a4aa23eacfd6ca215b72ae8/xilinx_bscan_spi.py#L359-L360

**Comment by jordens** [comment]
Can this be closed?

**Comment by duqiang** [comment]
Yes please. Thanks for your help.

**Pull request closed without merging**
